### ISSUE TITLE
ImportError: cannot import name 'VectorQuantizer2' from 'taming.modules.vqvae.quantize' (/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/taming/modules/vqvae/quantize.py)

### ISSUE THREAD

**Issue by Aditya-Bahl** [rinongal/textual_inversion#58]
Get this error when trying to invert an image during the usage step. Please help

**Comment by rinongal** [comment]
Just to make sure: Training worked correctly, and now when you're trying to use the token it is failing with this error, or are you failing on training?

Could you please paste the full error trace? I'll try to go over it first thing in the morning.

**Comment by Aditya-Bahl** [comment]
It is failing on training. Please see below. 

(ldm) Adityas-MacBook-Pro-2:textual_inversion adityabahl-mp$ python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n g --gpus 0, --data_root sample_images --init_word glass
Global seed set to 23
Running on GPUs 0,
Loading model from models/ldm/text2img-large/model.ckpt
Traceback (most recent call last):
  File "main.py", line 639, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "main.py", line 39, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/Users/adityabahl-mp/textual_inversion/textual_inversion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "/Users/adityabahl-mp/textual_inversion/textual_inversion/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/opt/anaconda3/envs/ldm/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/adityabahl-mp/textual_inversion/textual_inversion/ldm/models/diffusion/ddpm.py", line 26, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/Users/adityabahl-mp/textual_inversion/textual_inversion/ldm/models/autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ImportError: cannot import name 'VectorQuantizer2' from 'taming.modules.vqvae.quantize' (/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/taming/modules/vqvae/quantize.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 854, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

**Comment by rinongal** [comment]
It seems like the taming transformers module wasn't downloaded and setup correctly. Could you try running the environment setup again and seeing if it spits out a warning?

Alternatively, you can try installing that specific module with: 
`pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers`

**Comment by Aditya-Bahl** [comment]
Hello,

Unfortunately, I cant even download the Vonda environment and it’s due to Apple’s M1 chip. Issues with cudatoolkit, tried a few things and one of my colleagues tried to replicate it as well and have not been successful yet. I am Really intrigued by this work and would love to be able to run it. If you have time to do a video call, would love to chat and get this working. 

Best,
Addy

**Comment by FreeBlues** [comment]
@isademigod Your solution is very helpful, thanks!

**Comment by 5i-wanna-be-the-666** [comment]
you should carry out pip install -e. tow times 
first in /path/to/textual_inversion
second in /path/to/textual_inversion/src/taming-transformers
