### ISSUE TITLE
NameError: name 'trainer' is not defined

### ISSUE THREAD

**Issue by fpena06** [rinongal/textual_inversion#67]
Hello, I'm seeing the following error. Thanks for your help.

```
!python3 ./main.py --base /content/stable-diffusion/configs/stable-diffusion/v1-finetune.yaml \
                                            -t \
                                            --actual_resume /content/stable-diffusion/models/ldm/text2img-large/model.ckpt \
                                            -n my_gargamel \
                                            --gpus 1, \
                                            --data_root /content/drive/MyDrive/AI/StableDiffusion/training \
                                            --init_word 'gargamel'
```

> Global seed set to 23
> Running on GPUs 1,
> Traceback (most recent call last):
>   File "./main.py", line 535, in <module>
>     model = instantiate_from_config(config.model)
>   File "/content/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
>     return get_obj_from_str(config["target"])(**config.get("params", dict()))
>   File "/content/stable-diffusion/ldm/models/diffusion/ddpm.py", line 448, in __init__
>     super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'embedding_reg_weight'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./main.py", line 740, in <module>
>     if trainer.global_rank == 0:
> NameError: name 'trainer' is not defined

**Comment by inspire-boy** [comment]
If you have only one GPU,modify '--gpus 1, \' ==> '--gpus 0, \' and try again.

**Comment by rinongal** [comment]
Is our repo sitting in your /content/stable-diffusion/ directory, or is that another directory with the original stable-diffusion code?
That error looks like you're trying to load our model over the original code.

**Comment by fpena06** [comment]
> If you have only one GPU,modify '--gpus 1, \' ==> '--gpus 0, \' and try again. 

I tired with 0, before trying with 1. Same error.

**Comment by fpena06** [comment]
> Is our repo sitting in your /content/stable-diffusion/ directory, or is that another directory with the original stable-diffusion code?
> That error looks like you're trying to load our model over the original code.
> 

It's actually from this repo.

https://github.com/sd-webui/stable-diffusion-webui

**Comment by rinongal** [comment]
Did you look at this link in their repo? https://github.com/hlky/sd-enable-textual-inversion

They are not my repo, so I'm not really sure what might be different in their setup etc. Probably better to follow their own instructions first.

**Comment by rinongal** [comment]
Closing due to lack of activity. Feel free to reopen if you still need help

**Comment by ChL-eng** [comment]
pip install --ignore-installed --upgrade tensorflow
