### ISSUE TITLE
NameError: name 'trainer' is not defined

### ISSUE THREAD

**Issue by EKZERSIS** [rinongal/textual_inversion#84]
```
(ldm) C:\Users\ekzer\stable_diffusion\textual_inversion-main>python main.py --base configs/stable-diffusion/v1-finetune.yaml -t --actual_resume models/ldm/text2img-large/modelSD.ckpt -n art --gpus 0, --data_root img/datasets/cat_statue --init_word art --placeholder_tokens "*art cat" --no-test
Global seed set to 23
Running on GPUs 0,
Traceback (most recent call last):
  File "main.py", line 535, in <module>
    model = instantiate_from_config(config.model)
  File "C:\Users\ekzer\stable_diffusion\textual_inversion-main\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\Users\ekzer\stable_diffusion\textual_inversion-main\ldm\models\diffusion\ddpm.py", line 448, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'embedding_reg_weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 740, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

**Comment by EKZERSIS** [comment]
modelSD.ckpt - it is a model SD v1.4

**Comment by rinongal** [comment]
Is textual_inversion-main a clone of this repo? The line you're failing on is line 448 in your code, but [line 459](https://github.com/rinongal/textual_inversion/blob/5862ea4e3500a1042595bc199cfe5335703a458e/ldm/models/diffusion/ddpm.py#L459) in the code in the repo. 

It looks like your ddpm.py file may not be up-to-date with what we use, and is missing some of our arguments.

**Comment by jpentland** [comment]
I get the same error on runpod

```
File "/opt/conda/envs/ldm/lib/python3.8/site-packages/omegaconf/_utils.py", line 821, in format_and_raise         _raise(ex, cause)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/omegaconf/_utils.py", line 719, in _raise                   raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace                           File "/opt/conda/envs/ldm/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl            node = self._get_node(key=key, throw_on_missing_key=True)                                                     File "/opt/conda/envs/ldm/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 470, in _get_node            raise ConfigKeyError(f"Missing key {key}")          omegaconf.errors.ConfigAttributeError: Missing key model    full_key: model                                         object_type=dict                                                                                            During handling of the above exception, another exception occurred:                                                                                                     Traceback (most recent call last):                        File "main.py", line 824, in <module>                     if trainer.global_rank == 0:                        NameError: name 'trainer' is not defined                <3361:/workspace/textual_inversion#
```

**Comment by rinongal** [comment]
@jpentland This looks like the code isn't pointed at a correct configuration yaml (it's missing the model section). Can you make sure it's targeting the right config, and that your config file wasn't changed?

**Comment by rinongal** [comment]
@wasyleque The error you are getting is this part: AssertionError: String 'io2233' maps to more than a single token. Please use another string

Basically it's telling you that your init word ("io2233") is not a single token word. You need to choose another initial word to start from, which roughly describes the concept (so if you're learning on a picture of a toy cat, you'd use 'cat' or 'toy' etc.).

**Comment by rinongal** [comment]
Closing due to lack of activity. Feel free to reopen if you need more help.

**Comment by shayan-shaikh** [comment]
Having the same issue.
Here are my screenshot logs : 
```
Global seed set to 23
Running on GPUs 0,
Loading model from D:/textual_inversion/models/ldm/text2img-large/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 872.30 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to C:\Users\Shayan/.cache\torch\hub\checkpoints\checkpoint_liberty_with_aug.pth
Traceback (most recent call last):
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\http\client.py", line 1007, in _send_output
    self.send(msg)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\http\client.py", line 947, in send
    self.connect()
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\http\client.py", line 1421, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 635, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "main.py", line 36, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "D:\textual_inversion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "D:\textual_inversion\ldm\models\diffusion\ddpm.py", line 473, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "D:\textual_inversion\ldm\models\diffusion\ddpm.py", line 558, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "D:\textual_inversion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "D:\textual_inversion\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\textual_inversion\ldm\modules\encoders\modules.py", line 7, in <module>
    import kornia
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\__init__.py", line 10, in <module>
    from . import (
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\augmentation\__init__.py", line 43, in <module>
    from .container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\augmentation\container\__init__.py", line 1, in <module>
    from .augment import AugmentationSequential
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\augmentation\container\augment.py", line 17, in <module>
    from .patch import PatchSequential
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\augmentation\container\patch.py", line 9, in <module>
    from kornia.contrib.extract_patches import extract_tensor_patches
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\contrib\__init__.py", line 4, in <module>
    from .image_stitching import ImageStitcher
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\contrib\image_stitching.py", line 7, in <module>
    from kornia.feature import LocalFeatureMatcher, LoFTR
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\feature\__init__.py", line 4, in <module>
    from .integrated import (
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\feature\integrated.py", line 52, in <module>
    class LAFDescriptor(nn.Module):
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\feature\integrated.py", line 65, in LAFDescriptor
    patch_descriptor_module: nn.Module = HardNet(True),
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\kornia\feature\hardnet.py", line 66, in __init__
    pretrained_dict = torch.hub.load_state_dict_from_url(
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\torch\hub.py", line 586, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\torch\hub.py", line 452, in download_url_to_file
    u = urlopen(req)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\Shayan\miniconda3\envs\ldm\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 850, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined
```

**Comment by Biondo27** [comment]
Same issue for me. Did anyone solve it?

**Comment by rinongal** [comment]
This seems to be a general CompVis Stable Diffusion issue. Please see https://github.com/CompVis/stable-diffusion/issues/537 for a possible fix.

**Comment by shayan-shaikh** [comment]
Thank you for helping with the above issue! It did help with the problem, now I'm getting this : 
```
python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune.yaml -t --actual_resume D:/textual_inversion/models/ldm/text2img-large/model.ckpt -n test --gpus 0, --data_root D:/textual_inversion/images --init_word "boy"
Global seed set to 23
Running on GPUs 0,
Loading model from D:/textual_inversion/models/ldm/text2img-large/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 872.30 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: 100%|██████████████████████████████████████████████████████████████████████████| 28.0/28.0 [00:00<?, ?B/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 226k/226k [00:00<00:00, 361kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 455k/455k [00:00<00:00, 514kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<?, ?B/s]
Restored from D:/textual_inversion/models/ldm/text2img-large/model.ckpt with 0 missing and 2 unexpected keys
Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates']
C:\Users\Shayan\miniconda3\envs\ldm\lib\site-packages\pytorch_lightning\loggers\test_tube.py:104: LightningDeprecationWarning: The TestTubeLogger is deprecated since v1.5 and will be removed in v1.7. We recommend switching to the `pytorch_lightning.loggers.TensorBoardLogger` as an alternative.
  rank_zero_deprecation(
Monitoring val/loss_simple_ema as checkpoint metric.
Merged modelckpt-cfg:
{'target': 'CSVLogger', 'params': {'dirpath': 'logs\\images2023-03-20T23-32-51_test\\checkpoints', 'filename': '{epoch:06}', 'verbose': True, 'save_last': True, 'monitor': 'val/loss_simple_ema', 'save_top_k': 1, 'every_n_train_steps': 500}}Traceback (most recent call last):
  File "main.py", line 762, in <module>
    trainer_kwargs["callbacks"] = [instantiate_from_config(
  File "main.py", line 762, in <listcomp>
    trainer_kwargs["callbacks"] = [instantiate_from_config(
  File "D:\textual_inversion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "D:\textual_inversion\ldm\util.py", line 89, in get_obj_from_str
    module, cls = string.rsplit(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 850, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

(ldm) D:\textual_inversion>
```

I checked [#CompVis271](https://github.com/CompVis/stable-diffusion/issues/271) but to no avail
