### ISSUE TITLE
No `test_dataloader()` method defined to run `Trainer.test`.

### ISSUE THREAD

**Issue by yanzengatsmu** [rinongal/textual_inversion#93]
I got this error when I try to invert. 
```
Saving latest checkpoint...

Traceback (most recent call last):
  File "main.py", line 809, in <module>
    trainer.test(model, data)
  File "/home/yzeng/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 911, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/home/yzeng/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/yzeng/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 954, in _test_impl
    results = self._run(model, ckpt_path=self.tested_ckpt_path)
  File "/home/yzeng/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1128, in _run
    verify_loop_configurations(self)
  File "/home/yzeng/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 42, in verify_loop_configurations
    __verify_eval_loop_configuration(trainer, model, "test")
  File "/home/yzeng/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 186, in __verify_eval_loop_configuration
    raise MisconfigurationException(f"No `{loader_name}()` method defined to run `Trainer.{trainer_method}`.")
pytorch_lightning.utilities.exceptions.MisconfigurationException: No `test_dataloader()` method defined to run `Trainer.test`.
```
I've tried to fix it but failed. I would really appreciate it if you can help with this problem.

**Comment by yanzengatsmu** [comment]
The error was raised when saving latest checkpoint.

**Comment by rinongal** [comment]
You can ignore this, or run the code `--no-test` at the end.
It's an LDM issue, and it happens _after_ training is done either way.
